language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-log-dev
      - libboost-iostreams-dev
      - libxerces-c-dev
      - cmake

before_install:
  - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - sudo tar xf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo make install
  - cd ..
  - wget https://github.com/quickfix/quickfix/archive/v.1.14.4.tar.gz
  - tar xf v.1.14.4.tar.gz 
  - cd quickfix-v.1.14.4
  - ./bootstrap
  - ./configure 
  - make 
  - sudo make install
  - cd ..
  - pip install --user cpp-coveralls

script:
  - export CXX=/usr/bin/g++-7
  - export CC=/usr/bin/gcc-7
  - mkdir build && cd build && cmake .. && make
  - mkdir build_coverage && cd build_coverage && cmake .. -DCMAKE_BUILD_TYPE=Debug -DFI2XML_COVERAGE=ON && make fix2xml_coverage

after_success:
  - coveralls --gcov-options '\-lp'
